#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import hashlib
import struct
import sys

ROOT = Path(__file__).resolve().parent.parent
ROM = ROOT.parent / "snowboardkids.z64"

EXPECTED_SHA1 = "1583bacc9046a360df8ea4d536942155247e154c"

# Verified from the matching decomp:
ASP_DATA_ROM = 0xE2B00
ASP_DATA_SIZE = 0x800

# aspMain executes at IMEM 0x1080 and is 0xE20 bytes long.
ASP_TEXT_START = 0x1080
ASP_TEXT_END = ASP_TEXT_START + 0xE20

# The dispatcher generated by RSPRecomp contains:
#   lh $2, 0x10($2)
#   jr $2
#
# That makes +0x10 from the loaded ucode-data base the primary table candidate.
PRIMARY_TABLE_OFFSET = 0x10
COMMAND_COUNT = 16

AUTO_TARGETS = {
    0x10C0, 0x1130, 0x1178, 0x1240, 0x1280, 0x12BC, 0x14FC,
    0x16F8, 0x1790, 0x1868, 0x18C8, 0x1B24, 0x1B8C, 0x1E10,
}

SBK2_REFERENCE_TARGETS = {
    0x1118, 0x1470, 0x11DC, 0x1B38, 0x1214, 0x187C, 0x1254, 0x12D0,
    0x12EC, 0x1328, 0x140C, 0x1294, 0x1E24, 0x138C, 0x170C, 0x144C,
}


def sha1(path: Path) -> str:
    h = hashlib.sha1()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def read_halfwords(data: bytes, offset: int, count: int) -> list[int]:
    return list(struct.unpack_from(f">{count}H", data, offset))


def is_text_target(value: int) -> bool:
    return ASP_TEXT_START <= value < ASP_TEXT_END and value % 4 == 0


def print_table(label: str, rom_offset: int, values: list[int]) -> None:
    print(label)
    print(f"  ROM offset: 0x{rom_offset:06X}")
    for i, value in enumerate(values):
        flags = []
        if value in AUTO_TARGETS:
            flags.append("auto")
        if value in SBK2_REFERENCE_TARGETS:
            flags.append("SBK2-exact")
        if value + 0x14 in SBK2_REFERENCE_TARGETS:
            flags.append("SBK2-0x14")
        suffix = f"  [{', '.join(flags)}]" if flags else ""
        print(f"  [{i:02d}] 0x{value:04X}{suffix}")


def main() -> int:
    if not ROM.is_file():
        print(f"Missing ROM: {ROM}", file=sys.stderr)
        return 1

    actual = sha1(ROM)
    if actual != EXPECTED_SHA1:
        print("ROM SHA-1 mismatch", file=sys.stderr)
        print(f"Expected: {EXPECTED_SHA1}", file=sys.stderr)
        print(f"Actual:   {actual}", file=sys.stderr)
        return 1

    rom = ROM.read_bytes()
    data = rom[ASP_DATA_ROM:ASP_DATA_ROM + ASP_DATA_SIZE]
    if len(data) != ASP_DATA_SIZE:
        print("Could not read complete aspMain ucode-data region", file=sys.stderr)
        return 1

    print("Snowboard Kids — aspMain audio command-table analysis")
    print("=" * 58)
    print(f"ROM verified        : {EXPECTED_SHA1}")
    print(f"aspMain data ROM    : 0x{ASP_DATA_ROM:06X}")
    print(f"ucode data size     : 0x{ASP_DATA_SIZE:X}")
    print(f"aspMain IMEM range  : 0x{ASP_TEXT_START:04X}-0x{ASP_TEXT_END - 1:04X}")
    print()

    primary = read_halfwords(data, PRIMARY_TABLE_OFFSET, COMMAND_COUNT)
    print_table(
        "Primary candidate from dispatcher offset +0x10",
        ASP_DATA_ROM + PRIMARY_TABLE_OFFSET,
        primary,
    )

    valid_primary = sum(is_text_target(x) for x in primary)
    print(f"  valid text targets: {valid_primary}/{COMMAND_COUNT}")
    print(f"  unique targets    : {len(set(primary))}/{COMMAND_COUNT}")
    print()

    # Search the full 0x800-byte ucode-data blob for 16-entry big-endian
    # halfword tables whose entries all point into aspMain IMEM.
    candidates: list[tuple[int, list[int], int]] = []
    for off in range(0, ASP_DATA_SIZE - COMMAND_COUNT * 2 + 1, 2):
        vals = read_halfwords(data, off, COMMAND_COUNT)
        valid = sum(is_text_target(x) for x in vals)
        if valid == COMMAND_COUNT:
            score = len(set(vals))
            candidates.append((off, vals, score))

    print("All 16-entry aligned target-table candidates")
    if not candidates:
        print("  none")
    else:
        for off, vals, unique_count in candidates:
            marker = " <== primary" if off == PRIMARY_TABLE_OFFSET else ""
            print(
                f"  ROM 0x{ASP_DATA_ROM + off:06X} / data+0x{off:03X}: "
                f"{unique_count} unique{marker}"
            )
            print("    " + " ".join(f"{x:04X}" for x in vals))

    print()
    if valid_primary == COMMAND_COUNT:
        print("RESULT: the dispatcher +0x10 region is a structurally valid 16-entry")
        print("RSP command jump table. These values are the leading candidates for")
        print("extra_indirect_branch_targets in Snowboard Kids 1.")
    else:
        print("RESULT: +0x10 is not a complete 16-entry text-target table.")
        print("Use the scanned candidates above before changing RSPRecomp config.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
